[package]
name = "file-searcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
eza = "0.21.1"
grep = "0.3.2"
grep-printer = "0.2.2"
ignore = "0.4.23"
ignore-files = "3.0.3"
infer = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
serial = "0.4.0"
